Web/Controllers/EventController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Core.Entities;
using Web.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Core.Interfaces;
using Microsoft.AspNetCore.Http;

namespace Web.Controllers
{
    public class EventController : Controller

    {
        private const string SessionID = "UserID";

        private readonly IUnitOfWork<Event> _event;
#pragma warning disable CS0618 // 'IHostingEnvironment' est obsolète : 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.'
        private readonly IHostingEnvironment _hosting;
#pragma warning restore CS0618 // 'IHostingEnvironment' est obsolète : 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.'

#pragma warning disable CS0618 // 'IHostingEnvironment' est obsolète : 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.'
        public EventController(IUnitOfWork<Event> eventt, IHostingEnvironment hosting)
#pragma warning restore CS0618 // 'IHostingEnvironment' est obsolète : 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.'
        {
            _event = eventt;
            _hosting = hosting;
        }

       // GET: PortfolioItems
        public IActionResult Index(int id)
        {
            var Porfoilios = _event.Entity.GetAll();



      
            return View(Porfoilios);


        }

        //GET: PortfolioItems/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventItem = _event.Entity.GetById(id);
            if (eventItem == null)
            {
                return NotFound();
            }

            return View(eventItem);
        }


        //GET: PortfolioItems/Create
        public IActionResult Create()
        {

            return View();
        }

        //POST: PortfolioItems/Create
        //To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EventViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.File != null)
                {
                    string uploads = Path.Combine(_hosting.WebRootPath, @"img\portfolio");
                    string fullPath = Path.Combine(uploads, model.File.FileName);
                    model.File.CopyTo(new FileStream(fullPath, FileMode.Create));
                }

                Event eventItem = new Event
                {
                    Id = (int)HttpContext.Session.GetInt32(SessionID),
                    EventName = model.EventName,
                    DateEvent = model.DateEvent,
                    DescriptionE = model.DescriptionE,
                    ImageEvent = model.File.FileName


                };

                _event.Entity.Insert(eventItem);
                _event.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

       // GET: PortfolioItems/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventItem = _event.Entity.GetById(id);
            if (eventItem == null)
            {
                return NotFound();
            }

            EventViewModel portfolioViewModel = new EventViewModel
            {
                Id = eventItem.Id,
                DescriptionE = eventItem.DescriptionE,
                ImageEvent = eventItem.ImageEvent,
                EventName = eventItem.EventName,
                DateEvent = eventItem.DateEvent

            };

            return View(portfolioViewModel);
        }

        //POST: PortfolioItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, EventViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.File != null)
                    {
                        string uploads = Path.Combine(_hosting.WebRootPath, @"img\portfolio");
                        string fullPath = Path.Combine(uploads, model.File.FileName);
                        model.File.CopyTo(new FileStream(fullPath, FileMode.Create));
                    }

                    Event eventItem = new Event
                    {
                        Id = model.Id,
                        EventName = model.EventName,
                        DateEvent = model.DateEvent,
                        DescriptionE = model.DescriptionE,
                        ImageEvent = model.File.FileName
                    };

                    _event.Entity.Update(eventItem);
                    _event.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PortfolioItemExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

       // GET: PortfolioItems/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventItem = _event.Entity.GetById(id);
            if (eventItem == null)
            {
                return NotFound();
            }

            return View(eventItem);
        }

       // POST: PortfolioItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _event.Entity.Delete(id);
            _event.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool PortfolioItemExists(int id)
        {
            return _event.Entity.GetAll().Any(e => e.Id == id);
        }
    }
}

Web/Controllers/PortfolioItemsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Core.Entities;
using Web.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Core.Interfaces;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using System;
using Infrastructure;

namespace Web.Controllers
{
    public class PortfolioItemsController : Controller

    {
        private readonly DataContext _db;
        private const string SessionIsAdmin = "IsAdmin";
        private const string SessionID = "UserID";
        private readonly IUnitOfWork<PortfolioItem> _portfolio;
        private readonly IUnitOfWork<Abonner> _abn;
        private readonly IUnitOfWork<Image> _image;




#pragma warning disable CS0618 // 'IHostingEnvironment' est obsolète : 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.'
        private readonly IHostingEnvironment _hosting;
      
#pragma warning restore CS0618 // 'IHostingEnvironment' est obsolète : 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.'

#pragma warning disable CS0618 // 'IHostingEnvironment' est obsolète : 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.'
        public PortfolioItemsController(IUnitOfWork<PortfolioItem> portfolio, IHostingEnvironment hosting,IUnitOfWork<Abonner>abn,DataContext db, IUnitOfWork<Image> image)
#pragma warning restore CS0618 // 'IHostingEnvironment' est obsolète : 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.'
        {
            _portfolio = portfolio;
            _hosting = hosting;
            _abn = abn;
            _db = db;
            _image = image;
        }

        // GET: PortfolioItems
        public IActionResult Index(int id)
        {


            if (this.HttpContext.Session.GetString(SessionIsAdmin).Equals("true"))
            {
                var Porfoilios = _portfolio.Entity.GetAll();

                return View(Porfoilios);
            }
            else


            {
                var Porfoilios = _portfolio.Entity.GetAll();
                return View(Porfoilios.Where(x => x.ResponsableID.Equals(this.HttpContext.Session.GetInt32(SessionID))));
            }

        }
        [HttpGet]
        public async Task<IActionResult> Index(string Tearm){

            ViewData["GetGardinDetails"] = Tearm;
            var xD = from x in _db.portfolioItems select x;

            if (!string.IsNullOrEmpty(Tearm))
            {
                xD = xD.Where(x => x.NomJardin.Contains(Tearm)|| x.AddressJ.Contains(Tearm));


            }
            return View(await xD.AsNoTracking().ToListAsync());



        }



        [HttpGet]

        // GET: PortfolioItems/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var portfolioItem = _portfolio.Entity.GetById(id);
            if (portfolioItem == null)
            {
                return NotFound();
            }

            return View(portfolioItem);
        }


        // GET: PortfolioItems/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: PortfolioItems/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PortfolioViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.File != null)
                {
                    string uploads = Path.Combine(_hosting.WebRootPath, @"img\portfolio");
                    string fullPath = Path.Combine(uploads, model.File.FileName);
                    model.File.CopyTo(new FileStream(fullPath, FileMode.Create));
                }

                PortfolioItem portfolioItem = new PortfolioItem
                {
                    ResponsableID = (int)HttpContext.Session.GetInt32(SessionID),
                    NumTel = model.NumTel,
                    NomJardin = model.NomJardin,
                    AddressJ = model.AddressJ,
                    Description = model.Description,
                    ImageUrl = model.File.FileName,


                };

                _portfolio.Entity.Insert(portfolioItem);
                _portfolio.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: PortfolioItems/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var portfolioItem = _portfolio.Entity.GetById(id);
            if (portfolioItem == null)
            {
                return NotFound();
            }

            PortfolioViewModel portfolioViewModel = new PortfolioViewModel
            {
                Id = portfolioItem.Id,
                ResponsableID = portfolioItem.Id,
                Description = portfolioItem.Description,
                ImageUrl = portfolioItem.ImageUrl,
                NumTel = portfolioItem.NumTel,
                NomJardin = portfolioItem.NomJardin,
                AddressJ = portfolioItem.AddressJ,

            };

            return View(portfolioViewModel);
        }

        // POST: PortfolioItems/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, PortfolioViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.File != null)
                    {
                        string uploads = Path.Combine(_hosting.WebRootPath, @"img\portfolio");
                        string fullPath = Path.Combine(uploads, model.File.FileName);
                        model.File.CopyTo(new FileStream(fullPath, FileMode.Create));
                    }

                    PortfolioItem portfolioItem = new PortfolioItem
                    {
                        Id = model.Id,
                        ResponsableID = model.Id,
                        NomJardin = model.NomJardin,
                        NumTel = model.NumTel,
                        AddressJ = model.AddressJ,
                        Description = model.Description,
                        ImageUrl = model.File.FileName,
                        EmailGaredn=model.EmailGaredn,

                    };

                    _portfolio.Entity.Update(portfolioItem);
                    _portfolio.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PortfolioItemExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var portfolioItem = _portfolio.Entity.GetById(id);
            if (portfolioItem == null)
            {
                return NotFound();
            }

            return View(portfolioItem);
        }

        // POST: PortfolioItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _portfolio.Entity.Delete(id);
            _portfolio.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool PortfolioItemExists(int id)
        {
            return _portfolio.Entity.GetAll().Any(e => e.Id == id);
        }



        //////////////subscribe
        ///
        public IActionResult Subscribe(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var portfolioItem = _portfolio.Entity.GetById(id);

            Abonner abonner = new Abonner

            {
                userID = (int)HttpContext.Session.GetInt32(SessionID),
                PortfolioItemID = portfolioItem.Id,
                date = DateTime.UtcNow.ToString(),
                 NomJardin= portfolioItem.NomJardin



            };

            _abn.Entity.Insert(abonner);
            _abn.Save();
            return RedirectToAction("Index", "Home");


            return View(abonner);
        }


        public IActionResult SubIndex(int id)
        {

            var portfolioItem = _portfolio.Entity.GetById(id);

            var Porfoilios = _abn.Entity.GetAll();
            return View(Porfoilios.Where(x => x.PortfolioItemID.Equals(portfolioItem.Id)));
       

        }

        // GET: sUBS/Delete/5
        public IActionResult SubsDelete(int? id)
               {
                   if (id == null)
                   {
                       return NotFound();
                   }

                   var subs = _abn.Entity.GetById(id);
                   if (subs == null)
                   {
                       return NotFound();
                   }

                   return View(subs);
               }

               // POST: sUBSDelete/5
               [HttpPost, ActionName("DeleteS")]
               [ValidateAntiForgeryToken]
               public IActionResult SubsDelete(int id)
               {
                   _abn.Entity.Delete(id);
                   _abn.Save();
                   return RedirectToAction(nameof(SubIndex));

Web/Views/PortfolioItems/Create.cshtml
@model PortfolioViewModel

@{
    ViewData["Title"] = "Create";
}

<div  style="margin:10%; padding:5%;">
    <h1>Create</h1>

    <h4>Garden</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label">Name Garden</label>
                    <input asp-for="NomJardin" class="form-control" />
                    <span asp-validation-for="NomJardin" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EmailGaredn" class="control-label"></label>
                    <input asp-for="EmailGaredn" class="form-control" />
                    <span asp-validation-for="EmailGaredn" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="NumTel" class="control-label"></label>
                    <input asp-for="NumTel" class="form-control" />
                    <span asp-validation-for="NumTel" class=" text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Address</label>
                    <input asp-for="AddressJ" class="form-control" />
                    <span asp-validation-for="AddressJ" class=" text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl" class="control-label"></label>
                    <input type="file" asp-for="File" class="form-control" />
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="ImageGalerie" class="btn btn-outline-dark">gARDINiMAGE</a>
        <a asp-action="Index" class="btn btn-outline-dark">Back to List</a>
    </div>
</div>

Web/Views/PortfolioItems/Details.cshtml
@model Core.Entities.PortfolioItem

@{ ViewData["Title"] = "Details"; }



<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link href="~/css/profil.css" rel="stylesheet">
<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img"style="width:150%;height:100%;">
                    <img src="~/img/portfolio/@Model.ImageUrl" alt="" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h5>
                        Welcome @Model.NomJardin
                    </h5>
                    <p class="proile-rating">RANKINGS : <span>@*@Model.Rating*@     </span></p>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div style="initial-letter-align:ideagraphic">
                    <a asp-action="SubIndex" asp-controller="PorfolioItems" class="btn btn-dark" style="widh:70%" asp-route-id="@Model.Id">Subscribers </a></div>
                  
                    <div>
                        
                        <a asp-action="Index" asp-controller="Event" class="btn btn-dark" style="widh:70%" asp-route-id="@Model.Id">Event Liste</a>
                    </div>
                    <div>
                        <a asp-action="Index" asp-controller="Employer" class="btn btn-dark" style="widh:70%" asp-route-id="@Model.Id">Employers List</a>

                    </div>


                    <a href=""></a><br />
                    <a href=""></a><br />
                    <a href=""></a><br />
                    <a href=""></a><br />
                    <a href=""></a><br />
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Name Garden</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.NomJardin</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email Garden <label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.EmailGaredn</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Phone</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.NumTel</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Location</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.AddressJ</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Description</label>
                            </div>
                            <div class="col-md-6">
                                <p>Web @Model.Description</p>
                            </div>
                        </div>
                    </div>
                    @*
            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <div class="row">
                    <div class="col-md-6">
                        <label>Date</label>
                    </div>
                    <div class="col-md-6">
                        <p>*********</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Hourly Rate</label>
                    </div>
                    <div class="col-md-6">
                        <p>10$/hr</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Total Projects</label>
                    </div>
                    <div class="col-md-6">
                        <p>230</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>English Level</label>
                    </div>
                    <div class="col-md-6">
                        <p>Expert</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Availability</label>
                    </div>
                    <div class="col-md-6">
                        <p>6 months</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label>Your Bio</label><br />
                        <p>Your detail description</p>
                    </div>
                </div>
            </div>
        </div>
                    *@
                </div>
        </div>
    </form>
    <div>
        <a asp-action="Index" class="btn btn-outline-dark">Back to List</a> 


    </div>

</div>

Web/Views/PortfolioItems/IndexImage.cshtml
@*@model ImageViewModel
    @{ ViewData["Title"] = "Index"; }


    <!-- Portfolio Section -->
    <section class="page-section portfolio" href="/PortfolioItems/Create">
        <div class="container">

            <!-- Portfolio Section Heading -->
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Home</h2>

            <!-- Icon Divider -->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- Portfolio Grid Items -->
            <div class="row">

                <!-- Portfolio Item 1 -->
                @foreach (var portfolioItem in Model.Images)
                {
    <div class="col-md-6 col-lg-4">
        <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#item-@portfolioItem.Id">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                <div class="portfolio-item-caption-content text-center text-white">
                    <i class="fas fa-plus fa-3x"></i>
                </div>
            </div>
            <img class="img-fluid" src="~/img/portfolio/@portfolioItem.ImageG_Url" alt="">
        </div>
    </div>      }

            </div>
            <!-- /.row -->

        </div>
    </section>

    <!-- About Section -->
    <section class="page-section bg-primary text-white mb-0" id="about">
        <div class="container">

            <!-- About Section Heading -->
            <h2 class="page-section-heading text-center text-uppercase text-white">About</h2>

            <!-- Icon Divider -->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- About Section Content -->
            <div class="row">
                <div class="col-lg-4 ml-auto" style="margin:auto">
                    <p class="lead">Our App is a plateform where both Parents and Kindergarten managers can create an account, add garden for managers and search for a garden to put in their children for parents. Also our plateform welcomes all visitors </p>
                </div>
            </div>

        </div>
    </section>




    <!-- Portfolio Modals -->
    <!-- Portfolio Modal 1 -->
    @foreach (var item in Model.Images)
    {
    <div class="portfolio-modal modal fade" id="item-@item.Id" tabindex="-1" role="dialog" aria-labelledby="portfolioModal1Label" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        <i class="fas fa-times"></i>
                    </span>
                </button>
                <div class="modal-body text-center">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">

                                <div class="divider-custom">
                                    <div class="divider-custom-line"></div>
                                    <div class="divider-custom-icon">
                                        <i class="fas fa-star"></i>
                                    </div>
                                    <div class="divider-custom-line"></div>
                                </div>
                                <!-- Portfolio Modal - Image -->
                                <img class="img-fluid rounded mb-5" src="~/img/portfolio/@item.ImageG_Url" alt="">
                                <!-- Portfolio Modal - Text -->
                                <p class="mb-5">@item.DateInsert</p>

                                <div class="text-center mt-4">
                                    <a href="/PortfolioItems/Details/@item.Id">
                                        <i class="fas fa-eye"></i>|
                                        <u class="fas fa-2x"></u>
                                        Plus de détaille
                                    </a>
                                </div>
                                <br />
                                <div>
                                    <button class="btn btn-primary" href="#" data-dismiss="modal">
                                        <i class="fas fa-times fa-fw"></i>
                                        Close Window
                                    </button>
                                </div>
                                <a asp-controller="PortfolioItems" asp-action="Subscribe" class="btn btn-outline-dark">Subscribe</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>}


*@